# Generated by Django 3.2.5 on 2021-07-26 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_dice', models.PositiveIntegerField(default=1)),
                ('dice_walls', models.PositiveIntegerField(choices=[(2, '2'), (3, '3'), (4, '4'), (6, '6'), (8, '8'), (10, '10'), (12, '12'), (20, '20'), (100, '100')])),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField()),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diceroller.choice')),
            ],
        ),
    ]
