# Generated by Django 3.2.5 on 2021-07-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diceroller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='dice_walls',
            field=models.PositiveIntegerField(choices=[(2, '2'), (3, '3'), (4, '4'), (6, '6'), (8, '8'), (10, '10'), (12, '12'), (20, '20'), (100, '100')], default=6),
        ),
    ]
