# Generated by Django 3.2.5 on 2021-07-27 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diceroller', '0002_alter_choice_dice_walls'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolledNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diceroller.results')),
            ],
        ),
    ]
