# Generated by Django 3.2.5 on 2021-08-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diceroller', '0004_auto_20210727_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='number_of_dice',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
